export const container = 'container d-flex flex-column align-items-center'
export const tableStyle = 'table text-center'
export const formButtonStyle = 'btn btn-sm btn-outline-dark'
export const confirmButtonStyle = 'btn btn-sm btn-dark me-2'
export const deleteButtonStyle = 'btn btn-sm btn-danger'